// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRXSlaveLeft1;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRXSlaveLeft2;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRXSlaveRight1;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRXSlaveRight2;
std::shared_ptr<frc::DoubleSolenoid> RobotMap::intakeIntakeDoubleSolenoid;





    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::DoubleSolenoid> RobotMap::climberDoubleSolenoid;
std::shared_ptr<frc::SpeedController> RobotMap::climberMotor;

void RobotMap::init() {

}
